spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/data
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      format_sql: true
server:
  port: 8088

telegram:
  bot:
    token: bot6322541444:AAECk6b4TfGNxkq6SuDORbtiPnbRv9Qa6u4
    chat_id: -4088217061
    message: "<b>Yêu cầu %s qua ngân hàng</b>\nUser: <b>%s</b>\nSố tiền: <b>%s</b>\nNgân hàng: <b>%s</b>\nSố tài khoản: <b>%s</b>\nNội dung: <b>%s</b>"
app:
  upload:
    dir: images/