spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/data
    driver-class-name: org.postgresql.Driver
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      format_sql: true
server:
  port: 8088

components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
security:
  - bearerAuth: []