spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/data
    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      format_sql: true
server:
  port: 8089